
version: "3"

services:
  db:
    image: postgres:12
    container_name: recsys_controltower_db
    environment:
      - POSTGRES_PASSWORD=postgres

  django_app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: recsys-controltower:latest
    container_name: recsys_controltower_app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - ENV=local
      - DJANGO_DB_HOST=db
      - DJANGO_DB_HOST_RO=db
      - DJANGO_DB_USER_RO=tyr
      - DJANGO_DB_PASSWORD_RO=henning
      - DEBUG=true
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID-dummy}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY-dummy}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN-dummy}
      - AWS_DEFAULT_REGION=eu-west-1
    volumes:
      - ./src:/backend/
    depends_on:
      - db
