# Generated by Django 4.1.5 on 2023-02-02 06:05

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateList',
            fields=[
                ('type', models.CharField(choices=[('EN', 'engage'), ('ST', 'static')], default='EN', max_length=2)),
                ('cid', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('articles', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('shuffle', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CandidateListForbidden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articles', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('max_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name_postfix', models.CharField(blank=True, default='', max_length=256)),
                ('split', models.IntegerField(default=1)),
                ('wait_for_reply', models.BooleanField()),
                ('use_context', models.BooleanField()),
                ('cache_minutes', models.IntegerField(default=180)),
                ('candidate_list_limit', models.IntegerField(default=0)),
                ('use_user_id', models.BooleanField(default=True)),
                ('use_global_cache_key', models.BooleanField()),
                ('remove_read', models.BooleanField()),
                ('remove_exposed', models.BooleanField()),
                ('throttling_timeout_sec', models.IntegerField(default=20)),
                ('candidate_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recsys_config.candidatelist')),
            ],
        ),
        migrations.CreateModel(
            name='ModelService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('health_check_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SegmentMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user_type', models.CharField(choices=[('ALL', 'ALL'), ('SSO_ID', 'SSO'), ('EB_ID', 'EB'), ('NO_CONSENT', 'NONE')], default='ALL', max_length=20)),
                ('relevance_segment', models.CharField(blank=True, max_length=255, null=True)),
                ('models', models.ManyToManyField(related_name='models', to='recsys_config.modeldefinition')),
            ],
        ),
        migrations.CreateModel(
            name='RecommenderVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('api_id', models.CharField(max_length=255)),
                ('cache_key', models.CharField(max_length=255)),
                ('model_selection_timeout_min', models.IntegerField()),
                ('allow_unhealthy', models.BooleanField()),
                ('segment_matches', models.ManyToManyField(related_name='segment_matches', to='recsys_config.segmentmatch')),
            ],
        ),
        migrations.AddField(
            model_name='modeldefinition',
            name='fallback_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fallback_model', to='recsys_config.modelservice'),
        ),
        migrations.AddField(
            model_name='modeldefinition',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recsys_config.modelservice'),
        ),
        migrations.AddField(
            model_name='candidatelist',
            name='forbidden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recsys_config.candidatelistforbidden'),
        ),
    ]
