# Generated by Django 4.1.5 on 2023-02-28 09:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recsys_config', '0002_alter_candidatelist_cid_alter_candidatelist_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeldefinition',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
